# HEMA - Home Energy Management Assistant
# Copyright (C) 2024-2026 Wooyoung Jung, HUBS Lab, University of Arizona
# Licensed under GPL-3.0. See LICENSE file for details.
# scripts/test_scenarios/scenarios/analysis.py
"""ANALYSIS category test scenarios - Analysis Agent Deep Testing."""
from ..models import TestScenario

ANALYSIS_SCENARIOS = [
    TestScenario(
        id="anlys_001",
        name="Load Energy Data Request",
        category="analysis",
        input_message="Load my energy data",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should trigger data loading for analysis",
    ),
    TestScenario(
        id="anlys_002",
        name="Overall Consumption Summary",
        category="analysis",
        input_message="Give me a summary of my energy consumption",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        expected_contains=["consumption", "kWh"],
        description="Should provide consumption summary",
    ),
    TestScenario(
        id="anlys_003",
        name="Appliance Breakdown Request",
        category="analysis",
        input_message="Show me my appliance breakdown",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        expected_contains=["appliance"],
        description="Should show appliance-level breakdown",
    ),
    TestScenario(
        id="anlys_004",
        name="TOU Analysis Request",
        category="analysis",
        input_message="Analyze my TOU costs",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        expected_contains=["TOU", "cost"],
        description="Should analyze time-of-use cost impact",
    ),
    TestScenario(
        id="anlys_005",
        name="Peak Usage Identification",
        category="analysis",
        input_message="When do I use the most energy?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        expected_contains=["peak", "usage"],
        description="Should identify peak usage times",
    ),
    TestScenario(
        id="anlys_006",
        name="Cost Estimate Request",
        category="analysis",
        input_message="Estimate my monthly energy bill",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        expected_contains=["$", "cost"],
        description="Should estimate monthly costs",
    ),
    TestScenario(
        id="anlys_007",
        name="Hourly Pattern Analysis",
        category="analysis",
        input_message="Show my hourly energy patterns",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should analyze hourly consumption patterns",
    ),
    TestScenario(
        id="anlys_008",
        name="High Consumer Identification",
        category="analysis",
        input_message="What's driving my high energy bills?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        expected_contains=["energy", "usage"],
        description="Should identify high-consumption factors",
    ),
    TestScenario(
        id="anlys_009",
        name="Comparative Analysis",
        category="analysis",
        input_message="How does my usage compare to average homes?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should provide comparative context",
    ),
    TestScenario(
        id="anlys_010",
        name="Recommendation Request",
        category="analysis",
        input_message="What recommendations do you have for me?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        expected_contains=["recommend"],
        description="Should provide personalized recommendations",
    ),
]
