# HEMA - Home Energy Management Assistant
# Copyright (C) 2024-2026 Wooyoung Jung, HUBS Lab, University of Arizona
# Licensed under GPL-3.0. See LICENSE file for details.
# scripts/test_scenarios/scenarios/classification.py
"""CLASSIFICATION category test scenarios - PERSONAL vs GENERAL routing."""
from ..models import TestScenario

CLASSIFICATION_SCENARIOS = [
    # --- General Knowledge Questions (should route to knowledge_agent) ---
    TestScenario(
        id="class_001",
        name="General TOU Question",
        category="classification",
        input_message="What is TOU pricing?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["time-of-use", "peak", "rate"],
        expected_not_contains=["your data", "your consumption"],
        expected_response="TOU (Time-of-Use) pricing is an electricity rate structure where the cost per kWh varies based on the time of day. Rates are typically highest during peak hours (usually afternoons and early evenings) when demand is greatest, and lowest during off-peak hours (nights and early mornings). This pricing encourages consumers to shift energy usage to off-peak times to save money.",
        description="Should route to knowledge agent AND explain TOU concept without user data",
    ),
    TestScenario(
        id="class_002",
        name="General Heat Pump Question",
        category="classification",
        input_message="How do heat pumps work?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["heat pump"],
        expected_response="Heat pumps work by transferring heat rather than generating it. In cooling mode, they extract heat from inside your home and release it outside. In heating mode, they reverse the process, extracting heat from outdoor air (even in cold weather) and moving it inside. This makes them 2-3 times more efficient than traditional electric heating systems.",
        description="Should route to knowledge agent AND provide educational content",
    ),
    TestScenario(
        id="class_003",
        name="General Energy Tips",
        category="classification",
        input_message="What are some tips for saving energy?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["energy", "save"],
        expected_response="Here are key energy-saving tips: 1) Set thermostat to 78°F in summer, 68°F in winter. 2) Use LED bulbs instead of incandescent. 3) Unplug devices when not in use to avoid phantom load. 4) Run dishwashers and laundry during off-peak hours. 5) Seal air leaks around windows and doors. 6) Use smart power strips. 7) Maintain HVAC filters regularly.",
        description="Should route to knowledge agent AND provide general tips",
    ),
    TestScenario(
        id="class_004",
        name="General Solar Question",
        category="classification",
        input_message="What are the benefits of solar panels?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["solar"],
        expected_response="Solar panels offer several benefits: 1) Reduced electricity bills by generating your own power. 2) Protection against rising energy costs. 3) Environmental benefits through clean, renewable energy. 4) Potential income through net metering (selling excess power back to the grid). 5) Increased home value. 6) Available tax credits and incentives can reduce installation costs.",
        description="Should route to knowledge agent AND explain solar benefits",
    ),
    TestScenario(
        id="class_005",
        name="General - Peak Hours Explanation",
        category="classification",
        input_message="What are peak hours?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["peak"],
        expected_response="Peak hours are the times when electricity demand and prices are highest, typically between 3 PM and 8 PM on weekdays. During these hours, utilities charge premium rates because power plants must work harder to meet demand. Off-peak hours (usually nights and early mornings) have lower rates. Shifting energy usage to off-peak times can significantly reduce your bills.",
        description="Should explain peak hours concept generically",
    ),
    TestScenario(
        id="class_006",
        name="General - Off-Peak Explanation",
        category="classification",
        input_message="What is off-peak pricing?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["off-peak"],
        expected_response="Off-peak pricing refers to lower electricity rates charged during periods of reduced demand, typically nights (after 9 PM) and early mornings (before 6 AM). These rates can be 30-50% cheaper than peak rates. Running high-energy appliances like EV chargers, dishwashers, and laundry during off-peak hours can lead to significant savings.",
        description="Should explain off-peak pricing concept",
    ),
    TestScenario(
        id="class_007",
        name="General - Demand Response",
        category="classification",
        input_message="What is demand response?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["demand"],
        expected_response="Demand response is a program where utilities ask customers to reduce electricity usage during peak demand periods (usually hot summer afternoons) to prevent blackouts. Participants receive incentives like bill credits for reducing consumption when requested. Smart thermostats and devices can automatically participate in these programs.",
        description="Should explain demand response concept",
    ),
    TestScenario(
        id="class_008",
        name="General - kWh Definition",
        category="classification",
        input_message="What is a kilowatt hour?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["kWh", "energy"],
        expected_response="A kilowatt-hour (kWh) is a unit of energy representing the consumption of 1,000 watts over one hour. For example, a 100-watt light bulb running for 10 hours uses 1 kWh. Your electricity bill is based on total kWh consumed. Average US homes use about 900 kWh per month. Understanding kWh helps you compare appliance efficiency and calculate energy costs.",
        description="Should explain kWh unit",
    ),
    TestScenario(
        id="class_009",
        name="General - Smart Grid",
        category="classification",
        input_message="How does the smart grid work?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["grid"],
        expected_response="The smart grid is a modernized electrical grid using digital technology for two-way communication between utilities and consumers. It enables real-time monitoring, automatic outage detection, integration of renewable energy sources, and dynamic pricing. Smart meters are a key component, allowing utilities to manage demand and consumers to track usage in real-time.",
        description="Should explain smart grid technology",
    ),
    TestScenario(
        id="class_010",
        name="General - EV Charging Basics",
        category="classification",
        input_message="How does EV charging work?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["charg", "EV"],
        expected_response="EV charging has three levels: Level 1 uses a standard 120V outlet (2-5 miles/hour), Level 2 uses 240V (10-30 miles/hour, typical home installation), and Level 3/DC Fast Charging (60-200 miles in 20-30 minutes, found at public stations). For home charging, scheduling during off-peak hours can save 30-50% on electricity costs.",
        description="Should explain EV charging concepts",
    ),
    TestScenario(
        id="class_011",
        name="General - Energy Efficiency Tips",
        category="classification",
        input_message="How can I make my home more energy efficient?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["energy", "efficient"],
        expected_response="To improve home energy efficiency: 1) Add insulation in attic and walls. 2) Seal air leaks around windows and doors. 3) Upgrade to Energy Star appliances. 4) Install a programmable thermostat. 5) Switch to LED lighting. 6) Use ceiling fans to reduce AC load. 7) Consider double-pane windows. 8) Maintain HVAC systems regularly. These improvements can reduce energy use by 20-30%.",
        description="Should provide general efficiency tips",
    ),
    TestScenario(
        id="class_012",
        name="General - Appliance Efficiency",
        category="classification",
        input_message="What makes an appliance energy efficient?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["efficien"],
        expected_response="Energy-efficient appliances use less electricity to perform the same task. Key factors include: 1) Energy Star certification (meets EPA efficiency standards). 2) Better insulation in refrigerators and water heaters. 3) Inverter technology in AC units. 4) Higher SEER ratings for cooling systems. 5) EnergyGuide labels show estimated annual energy use. Efficient appliances cost more upfront but save money long-term.",
        description="Should explain appliance efficiency concepts",
    ),

    # --- Personal Analysis Questions (should route to analysis_agent) ---
    TestScenario(
        id="class_020",
        name="Personal Rate Question",
        category="classification",
        input_message="What's my utility rate?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for user-specific rate information",
    ),
    TestScenario(
        id="class_021",
        name="Personal Consumption Analysis",
        category="classification",
        input_message="Analyze my energy consumption",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for personal data analysis",
    ),
    TestScenario(
        id="class_022",
        name="Personal Peak Hours",
        category="classification",
        input_message="Show me my peak usage hours",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent to analyze user's peak usage patterns",
    ),
    TestScenario(
        id="class_023",
        name="Personal Appliance Comparison",
        category="classification",
        input_message="Which of my appliances uses the most energy?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent to compare user's appliance consumption",
    ),
    TestScenario(
        id="class_024",
        name="Personal - Monthly Bill",
        category="classification",
        input_message="How much is my energy bill this month?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for bill estimation",
    ),
    TestScenario(
        id="class_025",
        name="Personal - Daily Usage",
        category="classification",
        input_message="Show me my daily energy usage",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for daily consumption data",
    ),
    TestScenario(
        id="class_026",
        name="Personal - HVAC Cost",
        category="classification",
        input_message="How much does my AC cost to run?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for HVAC cost analysis",
    ),
    TestScenario(
        id="class_027",
        name="Personal - Weekend vs Weekday",
        category="classification",
        input_message="Compare my weekend and weekday energy usage",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for temporal comparison",
    ),
    TestScenario(
        id="class_028",
        name="Personal - High Usage Days",
        category="classification",
        input_message="What were my highest usage days?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for peak day identification",
    ),
    TestScenario(
        id="class_029",
        name="Personal - Cost Breakdown",
        category="classification",
        input_message="Give me a breakdown of my energy costs",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for cost breakdown",
    ),
    TestScenario(
        id="class_030",
        name="Personal - TOU Impact",
        category="classification",
        input_message="How much am I paying during peak hours?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for TOU cost analysis",
    ),
    TestScenario(
        id="class_031",
        name="Personal - Savings Potential",
        category="classification",
        input_message="How much could I save by shifting my usage?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for savings calculation",
    ),
    TestScenario(
        id="class_032",
        name="Personal - Usage Trend",
        category="classification",
        input_message="Is my energy usage going up or down?",
        expected_agent="analysis_agent",
        expected_scope="PERSONAL",
        description="Should route to analysis agent for trend analysis",
    ),
]
