# HEMA - Home Energy Management Assistant
# Copyright (C) 2024-2026 Wooyoung Jung, HUBS Lab, University of Arizona
# Licensed under GPL-3.0. See LICENSE file for details.
# scripts/test_scenarios/scenarios/control.py
"""CONTROL category test scenarios - Device Management."""
from ..models import TestScenario

CONTROL_SCENARIOS = [
    # --- Device Status Queries ---
    TestScenario(
        id="ctrl_001",
        name="Thermostat Status Query",
        category="control",
        input_message="What's the thermostat set to?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["temperature", "°F"],
        description="Should return current/target temperature values",
    ),
    TestScenario(
        id="ctrl_002",
        name="EV Charger Status",
        category="control",
        input_message="What's the status of my EV charger?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["battery", "charg"],
        description="Should show battery level and charging status",
    ),
    TestScenario(
        id="ctrl_003",
        name="Pool Pump Status",
        category="control",
        input_message="Is my pool pump running?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["pool", "pump"],
        description="Should indicate pump running status (on/off/speed)",
    ),
    TestScenario(
        id="ctrl_004",
        name="Water Heater Status",
        category="control",
        input_message="What's the water heater temperature?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["water heater", "°F"],
        description="Should show water heater temperature",
    ),
    TestScenario(
        id="ctrl_005",
        name="Dishwasher Status",
        category="control",
        input_message="What's the status of my dishwasher?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["dishwasher"],
        description="Should return dishwasher status using generic tool",
    ),
    TestScenario(
        id="ctrl_006",
        name="Washing Machine Status",
        category="control",
        input_message="Is the washing machine running?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["wash"],
        description="Should show washing machine status",
    ),
    TestScenario(
        id="ctrl_007",
        name="Dryer Status",
        category="control",
        input_message="Check my dryer status",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["dryer"],
        description="Should show dryer status",
    ),
    TestScenario(
        id="ctrl_008",
        name="Refrigerator Status",
        category="control",
        input_message="What's my fridge temperature?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["refrigerator", "°F"],
        description="Should show refrigerator temperature using alias matching",
    ),
    TestScenario(
        id="ctrl_009",
        name="Solar System Status",
        category="control",
        input_message="How much solar power am I generating?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["solar", "kW"],
        description="Should show current solar production",
    ),
    TestScenario(
        id="ctrl_010",
        name="Oven Status",
        category="control",
        input_message="Is the oven on?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["oven"],
        description="Should show oven status",
    ),

    # --- Device Control Actions ---
    TestScenario(
        id="ctrl_020",
        name="Set Temperature Command",
        category="control",
        input_message="Set the temperature to 72 degrees",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["72", "temperature"],
        description="Should confirm temperature change to 72°F",
    ),
    TestScenario(
        id="ctrl_021",
        name="Thermostat Mode Change - Heat",
        category="control",
        input_message="Switch the thermostat to heat mode",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["heat", "mode"],
        description="Should confirm mode change to heat",
    ),
    TestScenario(
        id="ctrl_022",
        name="Thermostat Mode Change - Cool",
        category="control",
        input_message="Put the AC in cooling mode",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["cool", "mode"],
        description="Should confirm mode change to cool",
    ),
    TestScenario(
        id="ctrl_023",
        name="Water Heater Vacation Mode",
        category="control",
        input_message="Set my water heater to vacation mode",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["vacation", "water heater"],
        description="Should confirm vacation mode activation",
    ),
    TestScenario(
        id="ctrl_024",
        name="EV Start Charging",
        category="control",
        input_message="Start charging my electric car now",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["charg"],
        description="Should start charging with confirmation",
    ),
    TestScenario(
        id="ctrl_025",
        name="EV Stop Charging",
        category="control",
        input_message="Stop charging my EV",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["stop", "charg"],
        description="Should stop charging with confirmation",
    ),
    TestScenario(
        id="ctrl_026",
        name="EV Set Charge Limit",
        category="control",
        input_message="Set my EV charge limit to 80%",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["80", "charg"],
        description="Should set charge limit with battery health tip",
    ),
    TestScenario(
        id="ctrl_027",
        name="Pool Pump Speed Adjustment",
        category="control",
        input_message="Set my pool pump to low speed",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["pool", "pump", "low"],
        description="Should set pump to low speed preset",
    ),
    TestScenario(
        id="ctrl_028",
        name="Pool Pump Turn Off",
        category="control",
        input_message="Turn off the pool pump",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["pool", "pump", "off"],
        description="Should turn off pool pump",
    ),
    TestScenario(
        id="ctrl_029",
        name="Turn Off Dryer",
        category="control",
        input_message="Turn off the clothes dryer",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["dryer", "off"],
        description="Should turn off dryer using generic control",
    ),
    TestScenario(
        id="ctrl_030",
        name="Turn On Dishwasher",
        category="control",
        input_message="Start the dishwasher",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["dishwasher"],
        description="Should start dishwasher",
    ),

    # --- Scheduling & Automation ---
    TestScenario(
        id="ctrl_040",
        name="Schedule EV Charging",
        category="control",
        input_message="Schedule my EV to charge at 10pm",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["schedule", "10"],
        description="Should confirm scheduled charging with TOU awareness",
    ),
    TestScenario(
        id="ctrl_041",
        name="Schedule EV Off-Peak",
        category="control",
        input_message="Schedule my car to charge during off-peak hours",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["schedule", "off-peak"],
        description="Should schedule for off-peak with rate info",
    ),
    TestScenario(
        id="ctrl_042",
        name="View Automation Rules",
        category="control",
        input_message="Show me my automation rules",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["rule", "automation"],
        description="Should display configured automation rules",
    ),
    TestScenario(
        id="ctrl_043",
        name="Schedule Thermostat Change",
        category="control",
        input_message="Schedule the AC to turn on at 3pm",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["schedule", "3"],
        description="Should schedule thermostat with TOU warning",
    ),

    # --- Device List & Energy Info ---
    TestScenario(
        id="ctrl_050",
        name="Device List Overview",
        category="control",
        input_message="What smart devices do I have?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["HVAC", "EV", "device"],
        description="Should list all device types",
    ),
    TestScenario(
        id="ctrl_051",
        name="All Connected Devices",
        category="control",
        input_message="List all my connected devices",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["device"],
        description="Should list all devices with status",
    ),
    TestScenario(
        id="ctrl_052",
        name="Device Energy Info - Single",
        category="control",
        input_message="How much energy does my refrigerator use?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["refrigerator", "kWh"],
        description="Should return refrigerator energy data",
    ),
    TestScenario(
        id="ctrl_053",
        name="All Devices Energy Summary",
        category="control",
        input_message="Give me an energy summary of all my devices",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["energy", "kWh", "device"],
        description="Should return comprehensive energy summary",
    ),
    TestScenario(
        id="ctrl_054",
        name="Device Actions Query",
        category="control",
        input_message="What can I do with my thermostat?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["action", "temperature"],
        description="Should list available thermostat actions",
    ),
    TestScenario(
        id="ctrl_055",
        name="EV Charger Actions",
        category="control",
        input_message="What actions can I perform on my EV charger?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["action", "charg"],
        description="Should list EV charger control options",
    ),

    # --- Device Alias Testing ---
    TestScenario(
        id="ctrl_060",
        name="Alias - Thermostat for HVAC",
        category="control",
        input_message="Check the thermostat status",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["temperature"],
        description="Should find HVAC using 'thermostat' alias",
    ),
    TestScenario(
        id="ctrl_061",
        name="Alias - AC for HVAC",
        category="control",
        input_message="Turn on the AC",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["HVAC"],
        description="Should find HVAC using 'AC' alias",
    ),
    TestScenario(
        id="ctrl_062",
        name="Alias - Washer for Washing Machine",
        category="control",
        input_message="Is the washer running?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["wash"],
        description="Should find washing machine using 'washer' alias",
    ),
    TestScenario(
        id="ctrl_063",
        name="Alias - Fridge for Refrigerator",
        category="control",
        input_message="What's my fridge set to?",
        expected_agent="control_agent",
        expected_scope="ACTION",
        expected_contains=["refrigerator"],
        description="Should find refrigerator using 'fridge' alias",
    ),
]
