# HEMA - Home Energy Management Assistant
# Copyright (C) 2024-2026 Wooyoung Jung, HUBS Lab, University of Arizona
# Licensed under GPL-3.0. See LICENSE file for details.
# scripts/test_scenarios/scenarios/conversation.py
"""CONVERSATION category test scenarios - Greetings, Help, Thanks, System Info."""
from ..models import TestScenario

CONVERSATION_SCENARIOS = [
    TestScenario(
        id="conv_001",
        name="Basic Greeting - Hello",
        category="conversation",
        input_message="Hello",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_contains=["HEMA"],
        expected_not_contains=["Error", "error", "exception"],
        description="Should greet user and mention HEMA system name",
    ),
    TestScenario(
        id="conv_002",
        name="Basic Greeting - Hi",
        category="conversation",
        input_message="Hi there!",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_contains=["HEMA"],
        expected_not_contains=["Error", "error"],
        description="Should respond to casual greeting without errors",
    ),
    TestScenario(
        id="conv_003",
        name="Basic Greeting - Good Morning",
        category="conversation",
        input_message="Good morning",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_contains=["HEMA"],
        expected_not_contains=["Error", "exception"],
        description="Should respond appropriately to time-based greeting",
    ),
    TestScenario(
        id="conv_004",
        name="Help Request - Capabilities",
        category="conversation",
        input_message="What can you do?",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_contains=["energy", "analysis"],
        expected_not_contains=["Error", "error"],
        description="Should list system capabilities including energy analysis features",
    ),
    TestScenario(
        id="conv_005",
        name="Help Request - How to Use",
        category="conversation",
        input_message="How do I use this system?",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_contains=["energy"],
        expected_not_contains=["Error", "error"],
        description="Should provide usage guidance for the HEMA system",
    ),
    TestScenario(
        id="conv_006",
        name="Help Request - Features",
        category="conversation",
        input_message="Tell me about your features",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_contains=["energy"],
        expected_not_contains=["Error", "failed"],
        description="Should describe HEMA system features",
    ),
    TestScenario(
        id="conv_007",
        name="Thanks Acknowledgment",
        category="conversation",
        input_message="Thank you!",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_not_contains=["Error", "error", "failed"],
        description="Should acknowledge thanks gracefully without errors",
    ),
    TestScenario(
        id="conv_008",
        name="Thanks - Variation",
        category="conversation",
        input_message="Thanks for the help!",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_not_contains=["Error", "exception"],
        description="Should handle thanks variation gracefully",
    ),
    TestScenario(
        id="conv_009",
        name="Goodbye Message",
        category="conversation",
        input_message="Goodbye",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_not_contains=["Error", "error"],
        description="Should handle goodbye gracefully",
    ),
    TestScenario(
        id="conv_010",
        name="Goodbye - See You Later",
        category="conversation",
        input_message="See you later!",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_not_contains=["Error", "exception"],
        description="Should handle casual goodbye",
    ),
    TestScenario(
        id="conv_011",
        name="System Identity Question",
        category="conversation",
        input_message="Who are you?",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_contains=["HEMA"],
        expected_not_contains=["Error", "error"],
        description="Should identify itself as HEMA energy assistant",
    ),
    TestScenario(
        id="conv_012",
        name="System Name Question",
        category="conversation",
        input_message="What is your name?",
        expected_agent="fallback_handler",
        expected_scope="CONVERSATION",
        expected_contains=["HEMA"],
        expected_not_contains=["Error", "error"],
        description="Should state its name as HEMA",
    ),
]
