# HEMA - Home Energy Management Assistant
# Copyright (C) 2024-2026 Wooyoung Jung, HUBS Lab, University of Arizona
# Licensed under GPL-3.0. See LICENSE file for details.
# scripts/test_scenarios/scenarios/knowledge.py
"""KNOWLEDGE category test scenarios - Knowledge Agent Deep Testing."""
from ..models import TestScenario

KNOWLEDGE_SCENARIOS = [
    TestScenario(
        id="know_001",
        name="Energy Star Explanation",
        category="knowledge",
        input_message="What is Energy Star certification?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["Energy Star"],
        expected_response="Energy Star is a U.S. EPA program that certifies products meeting strict energy efficiency guidelines. Energy Star appliances use 10-50% less energy than standard models. Look for the Energy Star label when buying refrigerators, washing machines, HVAC systems, TVs, and other appliances. The EnergyGuide yellow label shows estimated annual energy costs.",
        description="Should explain Energy Star program",
    ),
    TestScenario(
        id="know_002",
        name="Net Metering Explanation",
        category="knowledge",
        input_message="How does net metering work?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["net metering"],
        expected_response="Net metering allows solar panel owners to sell excess electricity back to the utility grid. When your panels produce more power than you use, the surplus flows to the grid and your meter runs backward, earning credits. At night or on cloudy days, you draw from the grid using those credits. This can significantly reduce or eliminate your electricity bill.",
        description="Should explain net metering concept",
    ),
    TestScenario(
        id="know_003",
        name="Power vs Energy",
        category="knowledge",
        input_message="What's the difference between kW and kWh?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["kW", "kWh"],
        expected_response="kW (kilowatt) measures power - the rate of energy use at any moment. kWh (kilowatt-hour) measures energy - total consumption over time. Think of it like a car: kW is your speed (how fast you're going), kWh is distance traveled (how far you went). A 2 kW appliance running for 3 hours uses 6 kWh. Your bill is based on kWh consumed.",
        description="Should explain power vs energy difference",
    ),
    TestScenario(
        id="know_004",
        name="SEER Rating Explanation",
        category="knowledge",
        input_message="What is a SEER rating?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["SEER"],
        expected_response="SEER (Seasonal Energy Efficiency Ratio) measures AC efficiency - higher is better. It's calculated by dividing cooling output by energy input over a season. Current minimum is SEER 14-15; high-efficiency units reach SEER 20-25. Each SEER point increase saves about 5-10% on cooling costs. When replacing an old SEER 10 unit with a SEER 16, expect 40% energy savings.",
        description="Should explain SEER rating for AC units",
    ),
    TestScenario(
        id="know_005",
        name="LED vs Incandescent",
        category="knowledge",
        input_message="Why are LED bulbs more efficient?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["LED", "efficien"],
        expected_response="LED bulbs convert about 90% of energy into light, while incandescent bulbs waste 90% as heat. A 10W LED produces the same light as a 60W incandescent. LEDs last 15,000-25,000 hours compared to 1,000 hours for incandescent. Though LEDs cost more upfront, they save $75-100 in electricity over their lifetime and reduce replacement hassle.",
        description="Should explain LED efficiency benefits",
    ),
    TestScenario(
        id="know_006",
        name="Phantom Load Explanation",
        category="knowledge",
        input_message="What is phantom load or standby power?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["standby", "power"],
        description="Should explain phantom load concept",
    ),
    TestScenario(
        id="know_007",
        name="Battery Storage Benefits",
        category="knowledge",
        input_message="Should I get a home battery system?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["battery"],
        description="Should explain home battery benefits",
    ),
    TestScenario(
        id="know_008",
        name="Insulation Tips",
        category="knowledge",
        input_message="How does insulation save energy?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["insulat"],
        description="Should explain insulation benefits",
    ),
    TestScenario(
        id="know_009",
        name="Smart Thermostat Benefits",
        category="knowledge",
        input_message="Are smart thermostats worth it?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["smart", "thermostat"],
        description="Should explain smart thermostat benefits",
    ),
    TestScenario(
        id="know_010",
        name="Tiered vs TOU Rates",
        category="knowledge",
        input_message="What's the difference between tiered and TOU rates?",
        expected_agent="knowledge_agent",
        expected_scope="GENERAL",
        expected_contains=["tiered", "TOU"],
        description="Should explain rate structure differences",
    ),
]
